//! `MergedDoc` -> wire-format markdown with `data-ai-grey` /
//! `data-transcript-link` marker spans.
//!
//! Source contract (the Legend's swatches): a block is `Source::User` only
//! when `diff::merge` found its text in the user's own notes; everything
//! else the LLM produced is `Source::AiGrey`. With empty notes the whole
//! document is AiGrey. Every AiGrey block, headings included, has its text
//! wrapped in `<span data-ai-grey data-ts="N">…</span>` so the editor
//! paints it grey; list items, paragraphs, blockquotes, and code blocks
//! additionally get a trailing
//! `<span data-transcript-link data-ts="N">↳ HH:MM</span>` deep-link.
//! Headings get no deep-link - they are inferred topic labels, not
//! transcript facts.

use crate::ast::{strip_markers, Block};
use crate::{MergedDoc, Source};

pub fn to_markdown(doc: &MergedDoc) -> String {
    let mut out = String::new();
    let mut in_list = false;
    for mb in &doc.blocks {
        // List items are emitted without a trailing blank line so sibling
        // bullets stay one list. Close the list before any other block, or
        // a following paragraph is glued onto the last bullet as a lazy
        // continuation line.
        let is_item = matches!(mb.block, Block::ListItem { .. });
        if in_list && !is_item {
            out.push('\n');
        }
        in_list = is_item;
        let rendered = match &mb.block {
            Block::Heading { level, text } => {
                format!("{} {}\n\n", "#".repeat(*level as usize), text)
            }
            Block::Paragraph { md } => format!("{md}\n\n"),
            Block::ListItem { md, depth } => {
                format!("{}- {md}\n", "  ".repeat(*depth as usize))
            }
            Block::CodeBlock { lang, body } => {
                format!("```{}\n{body}\n```\n\n", lang.as_deref().unwrap_or(""))
            }
            Block::BlockQuote { md } => format!("> {md}\n\n"),
            Block::Hr => "---\n\n".into(),
        };
        let with_marks = match (&mb.source, &mb.block) {
            (Source::User, _) => rendered,
            (Source::AiGrey { transcript_ts_sec }, Block::Heading { level, text }) => {
                // Match on the block, not the rendered string: the old
                // `strip_prefix("## ")` check let h1/h3 fall through to the
                // paragraph branch and come out as a literal "# text" line.
                format!(
                    "{} <span data-ai-grey data-ts=\"{transcript_ts_sec}\">{}</span>\n\n",
                    "#".repeat(*level as usize),
                    html_escape::encode_safe(&strip_markers(text))
                )
            }
            (Source::AiGrey { transcript_ts_sec }, _) => {
                wrap_ai(&rendered, *transcript_ts_sec, &mb.user_runs)
            }
        };
        out.push_str(&with_marks);
    }
    out
}

fn wrap_ai(rendered: &str, ts: u64, user_runs: &[(usize, usize)]) -> String {
    let mins = ts / 60;
    let secs = ts % 60;
    let stamp = format!("{:02}:{:02}", mins, secs);
    // The enhance prompt asks the LLM to emit its OWN
    // `<span data-ai-grey>` / `<span data-transcript-link>` markers, and
    // weaker models (e.g. Minimax) reproduce that scaffolding literally in
    // the bullet body. We own the wrapping, so strip any wire-format spans
    // the model emitted before we escape + re-wrap. Without this, the raw
    // markup gets HTML-escaped (`&lt;span…&gt;`) and double-wrapped,
    // surfacing literal `<span data-ai-grey …>` text in the user's notes.
    // strip_markers only removes OUR wire-format spans; a hallucinated
    // `<script>` survives stripping and is still escaped below (BL-2).
    let stripped = strip_markers(rendered);
    let trim = stripped.trim_end_matches('\n');
    let suffix_node = format!(r#"<span data-transcript-link data-ts="{ts}">↳ {stamp}</span>"#);
    // Nested items render as "  - md"; keep the indent outside the span.
    let indent_len = trim.len() - trim.trim_start().len();
    let (indent, body) = trim.split_at(indent_len);
    if let Some(inner) = body.strip_prefix("- ") {
        // BL-2: The `inner` text comes from the LLM output (untrusted).
        // Escape angle brackets/quotes so the LLM cannot inject a raw
        // <script>/<img onerror=...> via a hallucinated bullet body. The
        // `<span data-ai-grey>` wrapper itself is generated by us with
        // controlled values, so it stays raw.
        if user_runs.is_empty() {
            let safe_inner = html_escape::encode_safe(inner);
            format!(
                "{indent}- <span data-ai-grey data-ts=\"{ts}\">{safe_inner} {suffix_node}</span>\n"
            )
        } else {
            format!("{indent}- {} {suffix_node}\n", paint(inner, ts, user_runs))
        }
    } else if user_runs.is_empty() {
        let safe_trim = html_escape::encode_safe(trim);
        format!("<span data-ai-grey data-ts=\"{ts}\">{safe_trim} {suffix_node}</span>\n\n")
    } else {
        format!("{} {suffix_node}\n\n", paint(trim, ts, user_runs))
    }
}

/// Escape `inner` and wrap everything OUTSIDE `user_runs` in ai-grey spans,
/// so the user's own words (the runs) come out bare and render ink while the
/// model's phrasing around them renders grey. Runs are byte offsets into
/// `inner` (computed by `diff` on the same marker-stripped text); anything
/// out of range or off a char boundary is skipped rather than panicked on.
fn paint(inner: &str, ts: u64, user_runs: &[(usize, usize)]) -> String {
    let grey = |s: &str| {
        if s.is_empty() {
            String::new()
        } else {
            format!(
                "<span data-ai-grey data-ts=\"{ts}\">{}</span>",
                html_escape::encode_safe(s)
            )
        }
    };
    let mut out = String::new();
    let mut pos = 0;
    for &(a, b) in user_runs {
        if a < pos || b <= a || b > inner.len() {
            continue;
        }
        if !inner.is_char_boundary(a) || !inner.is_char_boundary(b) {
            continue;
        }
        out.push_str(&grey(&inner[pos..a]));
        out.push_str(&html_escape::encode_safe(&inner[a..b]));
        pos = b;
    }
    out.push_str(&grey(&inner[pos..]));
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::Block;
    use crate::MergedBlock;

    fn ai(block: Block) -> MergedBlock {
        MergedBlock {
            block,
            source: Source::AiGrey {
                transcript_ts_sec: 24,
            },
            user_runs: Vec::new(),
        }
    }

    #[test]
    fn woven_user_words_render_bare_between_grey_spans() {
        let mut mb = ai(Block::ListItem {
            md: "Rollout: 25% on Monday the 5th, then 50% the following week".into(),
            depth: 1,
        });
        mb.user_runs = vec![(9, 22)];
        let md = to_markdown(&MergedDoc { blocks: vec![mb] });
        assert_eq!(
            md,
            "  - <span data-ai-grey data-ts=\"24\">Rollout: </span>25% on Monday\
             <span data-ai-grey data-ts=\"24\"> the 5th, then 50% the following week</span> \
             <span data-transcript-link data-ts=\"24\">↳ 00:24</span>\n"
        );
    }

    #[test]
    fn a_paragraph_after_a_list_does_not_lazy_continue_the_bullet() {
        let doc = MergedDoc {
            blocks: vec![
                ai(Block::ListItem {
                    md: "from the transcript".into(),
                    depth: 0,
                }),
                MergedBlock {
                    block: Block::Paragraph {
                        md: "my own line".into(),
                    },
                    source: Source::User,
                    user_runs: Vec::new(),
                },
            ],
        };
        let md = to_markdown(&doc);
        assert!(
            md.contains("</span>\n\nmy own line"),
            "blank line must close the list, got:\n{md}"
        );
    }

    /// Empty notes => every block is AiGrey, and the editor can only paint a
    /// heading grey if the wire format marks it. h1/h3 previously fell
    /// through to the paragraph branch and rendered as a literal "# text".
    #[test]
    fn ai_headings_are_marked_grey_without_a_deep_link() {
        let doc = MergedDoc {
            blocks: vec![
                ai(Block::Heading {
                    level: 1,
                    text: "Team <b>updates</b>".into(),
                }),
                ai(Block::Heading {
                    level: 3,
                    text: "Launch".into(),
                }),
                MergedBlock {
                    block: Block::Heading {
                        level: 2,
                        text: "Mine".into(),
                    },
                    source: Source::User,
                    user_runs: Vec::new(),
                },
            ],
        };
        let md = to_markdown(&doc);
        assert_eq!(
            md,
            "# <span data-ai-grey data-ts=\"24\">Team &lt;b&gt;updates&lt;&#x2F;b&gt;</span>\n\n\
             ### <span data-ai-grey data-ts=\"24\">Launch</span>\n\n\
             ## Mine\n\n"
        );
    }
}
