[package]
name = "yogurt-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tokio = { workspace = true }
axum = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rust-embed = { workspace = true }
reqwest = { workspace = true }
mime_guess = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
reqwest = { workspace = true }
